### ISSUE TITLE
php版输入的steps与实际显示不符

### ISSUE THREAD

**Issue by lbs1412** [Evilmass/HackWechatRun#6]
比如刷了98800步，发现只有18800步，刷很大的数据才会到98800...是前天测试的，现在应该没问题啦，大佬加油！很喜欢这种从简陋到一步一步完善的程序设计方法，有一个想法实现了基本功能之后再增添新的功能，到最后就是一个很完美的程序了，膜并学习中

**Comment by Evilmass** [comment]
可能是乐动力服务器的问题
