### ISSUE TITLE
为什么不用 AJAX 作 POST 提交？

### ISSUE THREAD

**Issue by g-plane** [Evilmass/HackWechatRun#8]
直接使用 `form` 元素的 POST 方法提交，会造成页面刷新，用户体验不是很好。建议用 AJAX 来 POST 避免刷新。如果可以，最好在前端加个提交是否成功的 toast。

**Comment by Evilmass** [comment]
因为不会AJAX（逃
刷步数这种东西提交一次就够了，所以没有考虑到这么多
校友？欢迎PR

**Comment by g-plane** [comment]
我根据 PHP 部分的代码弄了一个不依赖后端的（就是不需要 PHP），稍后发 PR。
是校友哦

**Comment by Evilmass** [comment]
Merged
